### ISSUE TITLE
`cell_census.get_anndata` should return obs columns and var columns used for filtering

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#56] opened 2022-12-23 22:32 UTC
**Issue**

`SOMADataFrame.read_as_pandas_all()` retrieves all columns used for filtering for example:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/29237819/209410094-056abc65-539a-49b9-8e55-10fb6377ae36.png">

in this case `feature_id` was included in the final object as it was used for filtering

However for the `cell_census.get_anndata()` method, this is not the case:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/29237819/209410593-dd0a2c67-fb4f-47fb-ae76-7deadf1332cc.png">

**Solution**

In `cell_census.get_anndata()` all columns used for filtering in `obs_value_filter` and `var_value_filter` must be included in the corresponding `anndata.AnnData.obs` and `anndata.Anndata.var` respectively

**Comment by atolopko-czi** [comment] 2023-01-04 19:20
There is some effort involved with implementing this, as it requires parsing the declarative query string. We do have the [BNF grammar](https://tiledb-inc-tiledb.readthedocs-hosted.com/projects/tiledb-py/en/stable/python-api.html#query-condition) for this, but is it worth doing this? 

I think there will be cases where a user might _not_ want all of the query columns in the result.

**Comment by bkmartinjr** [comment] 2023-01-04 19:40
I think this is a SOMA bug/inconsistency - shouldn't be hard to fix.  I will get to it soon.

**Comment by bkmartinjr** [comment] 2023-01-19 17:16
Root cause: single-cell-data/TileDB-SOMA#755

**Comment by bkmartinjr** [comment] 2023-01-19 21:49
this is fixed in `tiledbsoma`, and will be available in the next release.

**Closed by bkmartinjr** 2023-01-19 21:49 UTC
Labels: bug
